name: Deploy ArgoCD to EKS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-2  # Update with your AWS region
  EKS_CLUSTER_NAME: my-eks-cluster  # Update with your EKS cluster name
  KUBECONFIG: /home/runner/.kube/config

jobs:
  deploy:
    name: Deploy ArgoCD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd || true  # Ignore if namespace already exists
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Wait for ArgoCD to be Ready
        run: |
          echo "Waiting for ArgoCD to be ready..."
          kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd

      - name: Retrieve ArgoCD Initial Admin Password
        run: |
          echo "Retrieving ArgoCD initial admin password..."
          kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode

      - name: Retrieve ArgoCD URL
        run: |
          ARGOCD_SERVER=$(kubectl get svc -n argocd argocd-server -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
          echo "ArgoCD is accessible at: https://$ARGOCD_SERVER"
